/**
 *
 * Assets like Illustration or Icon
 */

export default Assets = {
  icon_verified_3x: require("../Assets/Images/Illustration/Icon/verified_3x.png"),
  icon_coin_small_3x: require("../Assets/Images/Illustration/Icon/coin_small_3x.png"),
  icon_bunga_big_3x: require("../Assets/Images/Illustration/Icon/bunga_big_3x.png"),
  icon_bunga_small_3x: require("../Assets/Images/Illustration/Icon/bunga_small_3x.png"),
  icon_cake_big_3x: require("../Assets/Images/Illustration/Icon/cake_big_3x.png"),
  icon_parcel_makanan_big_3x: require("../Assets/Images/Illustration/Icon/parcel_makanan_big_3x.png"),
  icon_search_big_3x: require("../Assets/Images/Illustration/Icon/search_big_3x.png"),
  icon_search_small_3x: require("../Assets/Images/Illustration/Icon/search_small_3x.png"),
  icon_bell_3x: require("../Assets/Images/Illustration/Icon/bell_3x.png"),
  icon_shopping_bag_3x: require("../Assets/Images/Illustration/Icon/shopping_bag_3x.png"),
  icon_map_pin_white_3x: require("../Assets/Images/Illustration/Icon/map_pin_white_3x.png"),
  icon_arrow_left_3x: require("../Assets/Images/Illustration/Icon/arrow_left_3x.png"),
  icon_cross_grey_small_3x: require("../Assets/Images/Illustration/Icon/cross_grey_small_3x.png"),
  icon_blink_3x: require("../Assets/Images/Illustration/Icon/blink_3x.png"),
  icon_rotated_left_arrow_dashed_line_3x: require("../Assets/Images/Illustration/Icon/rotated_left_arrow_dashed_line_3x.png"),
  icon_start_full_filled_small_3x: require("../Assets/Images/Illustration/Icon/start_full_filled_small_3x.png"),
  under_construction_3x: require("../Assets/Images/Illustration/under_construction_3x.png"),
  icon_map_pin_grey_3x: require("../Assets/Images/Illustration/Icon/map_pin_grey_3x.png"),
  icon_navigation_3x: require("../Assets/Images/Illustration/Icon/navigation_3x.png"),
  pin_map_with_human_big_3x: require("../Assets/Images/Illustration/pin_map_with_human_big_3x.png"),
  check_mark_outline_primary_big_3x: require("../Assets/Images/Illustration/check_mark_outline_primary_big_3x.png"),
  frown_big_color_3x: require("../Assets/Images/Illustration/frown_big_3x.png"),
  icon_chevron_right_grey_3x: require("../Assets/Images/Illustration/Icon/chevron_right_grey_3x.png"),
  icon_tabler_seeding_white_big_3x: require("../Assets/Images/Illustration/Icon/tabler_seeding_white_big_3x.png"),
  icon_coin_grey_3x: require("../Assets/Images/Illustration/Icon/coin_grey_3x.png"),
  icon_discount_grey_3x: require("../Assets/Images/Illustration/Icon/discount_grey_3x.png"),
  icon_flower_lotus_grey_3x: require("../Assets/Images/Illustration/Icon/flower_lotus_grey_3x.png"),
  icon_gift_grey_3x: require("../Assets/Images/Illustration/Icon/gift_grey_3x.png"),
  icon_headset_grey_3x: require("../Assets/Images/Illustration/Icon/headset_grey_3x.png"),
  icon_logout_grey_3x: require("../Assets/Images/Illustration/Icon/log_out_grey_3x.png"),
  icon_profile_grey_3x: require("../Assets/Images/Illustration/Icon/profile_grey_3x.png"),
  icon_clipboard_grey_3x: require("../Assets/Images/Illustration/Icon/clipboard_grey_3x.png"),
  icon_building_house_grey_3x: require("../Assets/Images/Illustration/Icon/building_house_grey_3x.png"),
  icon_bell_grey_3x: require("../Assets/Images/Illustration/Icon/bell_grey_3x.png"),
  icon_arrow_left_white_3x: require("../Assets/Images/Illustration/Icon/arrow_back_white_small_3x.png"),
  icon_map_pin_primary_gradient_3x: require("../Assets/Images/Illustration/Icon/map_pin_primary_gradient_3x.png"),
  icon_map_pin_primary_gradient_1x: require("../Assets/Images/Illustration/Icon/map_pin_primary_gradient_1x.png"),
  icon_discount_2_white_3x: require("../Assets/Images/Illustration/Icon/discount_2_white_3x.png"),
  noImageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/390px-No-Image-Placeholder.svg.png",
  thumb_up_color_3x: require("../Assets/Images/Illustration/thumb_up_color_3x.png"),
  cs_color_3x: require("../Assets/Images/Illustration/cs_color_3x.png"),
  logo_wa_color_3x: require("../Assets/Images/Illustration/Icon/logo_wa_color_3x.png"),
  payment_success: require("../Assets/Images/Illustration/payment_success_3x.png"),
  payment_error: require("../Assets/Images/Illustration/payment_failed_3x.png"),
  payment_waiting: require("../Assets/Images/Illustration/payment_waiting_3x.png"),
  coin: require("../Assets/Images/Illustration/Icon/coins.png"),
  money: require("../Assets/Images/Illustration/Icon/money.png"),
  check: require("../Assets/Images/Illustration/Icon/Check.png"),
  pajak_waiting: require("../Assets/Images/Illustration/Icon/Waiting.png"),
  pajak_sent: require("../Assets/Images/Illustration/Icon/Completed-Sent.png"),
  sedih: require("../Assets/Images/Illustration/Icon/Frown.png"),
  BackgroundBantuan: require("../Assets/Images/Illustration/BackgroundBantuan.png"),
  faq_1: require("../Assets/Images/Illustration/Icon/faq_1.png"),
  faq_2: require("../Assets/Images/Illustration/Icon/faq_2.png"),
  faq_3: require("../Assets/Images/Illustration/Icon/faq_3.png"),
  faq_4: require("../Assets/Images/Illustration/Icon/faq_4.png"),
  faq_5: require("../Assets/Images/Illustration/Icon/faq_5.png"),
  faq_6: require("../Assets/Images/Illustration/Icon/faq_6.png"),
  faq_7: require("../Assets/Images/Illustration/Icon/faq_7.png"),
  faq_8: require("../Assets/Images/Illustration/Icon/faq_8.png"),
  bannerAbout: require("../Assets/Images/Illustration/Banner-about.png"),
  about1: require("../Assets/Images/Illustration/about1.png"),
  about2: require("../Assets/Images/Illustration/about2.png"),
  about3: require("../Assets/Images/Illustration/about3.png"),
  welcome: require("../Assets/Images/Illustration/welcome.png"),
  avaDummyMen:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf4TMi3TelAnO24U64w75_uJyAAMKTDcp3uA&usqp=CAU",
  noAvaImg:
    "https://instagram.fsac1-2.fna.fbcdn.net/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=instagram.fsac1-2.fna.fbcdn.net&_nc_cat=1&_nc_ohc=UCNRtLPA8N8AX8S2NoM&edm=AEsR1pMBAAAA&ccb=7-5&ig_cache_key=YW5vbnltb3VzX3Byb2ZpbGVfcGlj.2-ccb7-5&oh=00_AT-XkKUHvX0yxZmd6elZkGKUUdE-tdYvelbEMNByF00phQ&oe=62DEA54F&_nc_sid=3f45ac",
  epReward: require("../Assets/Images/Illustration/ep_modal_feature_image.png"),
  no_saved_address_3x: require("../Assets/Images/Illustration/no_saved_address_3x.png"),
  empty_trans: require("../Assets/Images/Illustration/EmptyState/empty_trans.png"),
  BNI: require("../Assets/Images/Illustration/bank/BNI.png"),
  MANDIRI: require("../Assets/Images/Illustration/bank/MANDIRI.png"),
  BCA: require("../Assets/Images/Illustration/bank/BCA.png"),
  BRI: require("../Assets/Images/Illustration/bank/BRI.png"),
  PERMATA: require("../Assets/Images/Illustration/bank/PERMATA.png"),
};
